services:
  mariadb:
    image: mariadb:11.5
    container_name: mysterria-archive-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - gateway-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysterria-archive-app
    restart: unless-stopped
    ports:
      - "${APP_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER:-mysterria-backend}
      SERVER_PORT: 8080
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - gateway-network

volumes:
  mariadb_data:
    driver: local

networks:
  gateway-network:
    external: true
    name: mysterria-gateway_gateway-network